server:
    port: 9091


spring:
    redis:
      host: 192.168.1.109
      port: 6379
      password: a1b2c3
      database: 1
      pool:
        max-active: 10
        min-idle: 2
    rabbitmq:
        listener:
            simple:
                acknowledge-mode: none




mq: 
    host: 192.168.1.109
    port: 5672
    username: lsq984
    password: 123456789
    vhost: /ExchangeVH_v2
    exchange: t_node_grp
    historicalMarketQueue: 
        name: HISTORICAL_MARKET
        routingKey: orderapi2order
    dayMarketQueue:
        name: DAY_MARKET
        routingKey: orderapi2order
        
        
ws:
  routingKey:
    marketServToWs: marketServ
        
candle:
    timeframes: M1,M5,M15,M30,H1,H4,H12,D1,W1,MN