spring:

  datasource:
    url: jdbc:mysql://192.168.1.109:3306/acae-sys?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456!Root
    driver-class-name: com.mysql.jdbc.Driver
    
server:
    port: 8081