spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:log4jdbc:mysql://192.168.1.109:3306/exchange?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456!Root
    driverClassName: net.sf.log4jdbc.DriverSpy
    
server:
    port: 8080