spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://192.168.1.222:3306/exchange?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456!Root
  redis:
    database: 1
    host: 192.168.1.222
    port: 6379
    password: a1b2c3
    
server:
    port: 9090